"""added admin table and changes on other models too

Revision ID: 4fe0d8519bc2
Revises: 3a84c53ff11f
Create Date: 2025-04-25 08:47:18.229845

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4fe0d8519bc2'
down_revision = '3a84c53ff11f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('category_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])
        batch_op.drop_column('created_by')

    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('admin_id', sa.Integer(), nullable=False))
        batch_op.drop_constraint('quiz_ibfk_1', type_='foreignkey')
        batch_op.create_foreign_key(None, 'admin', ['admin_id'], ['id'])
        batch_op.drop_column('created_by')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('quiz', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('quiz_ibfk_1', 'user', ['created_by'], ['id'])
        batch_op.drop_column('admin_id')

    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_by', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('category_ibfk_1', 'user', ['created_by'], ['id'])
        batch_op.drop_column('admin_id')

    op.drop_table('admin')
    # ### end Alembic commands ###
