"""updated category table

Revision ID: 640867cc7e61
Revises: 0b2d370373f4
Create Date: 2025-04-29 16:48:43.015264

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '640867cc7e61'
down_revision = '0b2d370373f4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.add_column(sa.Column('icon', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('category', schema=None) as batch_op:
        batch_op.drop_column('is_active')
        batch_op.drop_column('icon')

    # ### end Alembic commands ###
